version: '3.4'

services:
  apache:
    build: .
    container_name: php
    restart: always
    ports:
      - '8010:80'
    volumes:
      - ./html:/var/www/html
#    depends_on:
#      - db
#    links:
#      - db

#  db:
#    container_name: mysql
#    image: mysql:5.7
#    restart: always
#    ports:
#      - '3306:3306'
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=banco_de_dados